version: '3'
services:
  backend:
    container_name: backend
    image: reviewbackend
    ports:
      - "${BACKEND_PORT}:3000"
    build:
      context: ./backend
      args:
        STAGE: ${STAGE}
    networks:
      - net
    depends_on:
      - db
  
  frontend:
    container_name: frontend
    image: review-frontend
    ports:
      - "${FRONTEND_PORT}:4200"
    build:
      context: ./packet-money
      args:
        STAGE: ${STAGE}
    depends_on: backend
    networks:
      - net
    
  database:
    image: mongo:4.0.3
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      -  "${MONGODB_PORT}:27017"
    volumes:
      - "~/app/${STAGE}/mongo:/data/db"
      - "./mongo-entrypoint:/docekr-entrypoint-initdb.d/:ro"
    networks:
      - net
    command: mongod 
networks:
  net: